language: java
jdk:
  - oraclejdk8
  - openjdk8

script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
      - oracle-java8-installer